### ISSUE TITLE
Add a readme to franka_description

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/python-example-droid-dataset#1]
https://github.com/rerun-io/python-example-droid-dataset/tree/master/franka_description

It's a bit unclear where it comes from, ideally it would be pulled in via requirements.txt, but at least we should document what's going on there.

**Comment by 02alexander** [comment]
I added a [README.md](https://github.com/rerun-io/python-example-droid-dataset/commit/3c9c7186df53b18e901a34a0af608b457bde16b7) in the folder that explains where it comes from. I don't think it would be possible to include it via requirements.txt since not a python package but a ROS package. I thought it would be best if the user doesn't have to do anything with ROS since it can be a tricky to install.
